

Word.create(kanji: "一", kana: "いち", english: "one")
Word.create(kanji: "二", kana: "に", english: "two")
Word.create(kanji: "三", kana: "さん", english: "three")
Word.create(kanji: "四", kana: "よん", english: "four")
Word.create(kanji: "五", kana: "ご", english: "five")
Word.create(kanji: "六", kana: "ろく", english: "six")
Word.create(kanji: "七", kana: "しち", english: "seven")
Word.create(kanji: "八", kana: "はち", english: "eight")
Word.create(kanji: "九", kana: "きゅう", english: "nine")
Word.create(kanji: "十", kana: "じゅう", english: "ten")
Word.create(kanji: "十一", kana: "じゅういち", english: "one")
Word.create(kanji: "十二", kana: "じゅうに", english: "two")
Word.create(kanji: "十三", kana: "じゅうさん", english: "three")
Word.create(kanji: "十四", kana: "じゅうよん", english: "four")
Word.create(kanji: "十五", kana: "じゅうご", english: "five")
Word.create(kanji: "十六", kana: "じゅうろく", english: "six")
Word.create(kanji: "十七", kana: "じゅうなな", english: "seven")
Word.create(kanji: "十八", kana: "じゅうはち", english: "eight")
Word.create(kanji: "十九", kana: "じゅうきゅう", english: "nine")
Word.create(kanji: "二十", kana: "にじゅうに", english: "ten")

